/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.PDC;

import javax.swing.*;
import java.awt.event.*;
import java.math.BigDecimal;

/**
 *
 * @author Hieu Nguyen
 */
public class BudgetPanel extends javax.swing.JPanel {

    private final PDC myController;


    /** The controller used to change and retrieve data. */
    //private final String myBudget;
    //private final String myBudget;





    public BudgetPanel(PDC myController) {
        this.myController = myController;
        initComponents();

        // Register hierarchy change listener
        // Register component listener
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                // Update labels when the panel becomes visible
                updateLabels();
            }
        });

// Update labels with initial values
        if(myController.getCurrProjectName() != null) {
            updateLabels();
        }
    }

    private void updateLabels() {
        // Get the updated values for budget, cost, and balance
        BigDecimal budget = myController.getProjectBudget();
        BigDecimal cost = myController.totalCost();
        BigDecimal balance = myController.calculateCurrentBudget(budget,cost);

        // Update the labels with the new values
        displayBudget.setText(budget.toString());
        displayCost.setText(cost.toString());
        displayBalance.setText(balance.toString());
        displayCost.setText(myController.totalCost().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Budget = new javax.swing.JLabel();
        currentBudget = new javax.swing.JLabel();
        moneySign1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moneySign3 = new javax.swing.JLabel();
        displayBalance = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        displayBudget = new javax.swing.JLabel();
        purchaseCost = new javax.swing.JLabel();
        displayCost = new javax.swing.JLabel();
        moneySign2 = new javax.swing.JLabel();
        editBudget = new javax.swing.JTextField();
        editBudgetButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Budget.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Budget.setText("Budget :");

        currentBudget.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentBudget.setText("Current Balance :");

        moneySign1.setText("$");
        moneySign1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel1.setText("Budget");

        moneySign3.setText("$");
        moneySign3.setToolTipText("");

        displayBalance.setText("balance");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmButton.setText("RECALCULATE");
        confirmButton.setActionCommand("CALCULATE");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        displayBudget.setText("budget");

        purchaseCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        purchaseCost.setText("Purchase cost :");

        displayCost.setText("Display cost");

        moneySign2.setText("$");

        editBudget.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editBudget.setText("Edit Budget");

        editBudgetButton.setText("Ok");
        editBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBudgetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(currentBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(moneySign3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(displayBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Budget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(moneySign1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(displayBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(60, 60, 60))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(confirmButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(editBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(purchaseCost)
                                                .addGap(3, 3, 3)
                                                .addComponent(moneySign2)
                                                .addGap(3, 3, 3)
                                                .addComponent(displayCost)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Budget, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneySign1)
                                        .addComponent(displayBudget))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(purchaseCost)
                                        .addComponent(displayCost)
                                        .addComponent(moneySign2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(currentBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneySign3)
                                        .addComponent(displayBalance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String budgetText = displayBudget.getText();
        String costText = displayCost.getText();

        try {
            BigDecimal budget = new BigDecimal(budgetText);
            BigDecimal cost = new BigDecimal(costText);

            // Update the purchase cost label with the updated total cost
            displayCost.setText(myController.totalCost().toString());
        } catch (NumberFormatException e) {
            // Handle invalid input
            JOptionPane.showMessageDialog(this, "Invalid budget or cost value. Please enter valid numbers.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if there was an error
        }

        // Retrieve the updated budget and cost values after the labels have been updated
        BigDecimal budget = new BigDecimal(displayBudget.getText());
        BigDecimal cost = new BigDecimal(displayCost.getText());

        // Get the updated balance
        BigDecimal balance = myController.calculateCurrentBudget(budget, cost);

        // Update the balance label
        displayBalance.setText(balance.toString());

        // Check if the current budget is negative and display a warning dialog if true
        if (balance.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "Warning: The current balance is negative.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void editBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String newBudgetText = editBudget.getText();

        try {
            BigDecimal newBudget = new BigDecimal(newBudgetText);

            // Update the budget value in the controller
            myController.setProjectBudget(newBudget);

            // Update the labels with the new budget and recalculate the balance
            updateLabels();
        } catch (NumberFormatException e) {
            // Handle invalid input
            JOptionPane.showMessageDialog(this, "Invalid budget value. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {

    }





    // Variables declaration - do not modify
    private javax.swing.JLabel Budget;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel currentBudget;
    private javax.swing.JLabel displayBalance;
    private javax.swing.JLabel displayBudget;
    private javax.swing.JLabel displayCost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel moneySign1;
    private javax.swing.JLabel moneySign2;
    private javax.swing.JLabel moneySign3;
    private javax.swing.JLabel purchaseCost;
    private javax.swing.JTextField editBudget;
    private javax.swing.JButton editBudgetButton;
    // End of variables declaration
}


/**private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {


}**/



