/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.PDC;

import javax.swing.*;
import java.math.BigDecimal;

/**
 *
 * @author Hieu Nguyen
 */
public class BudgetPanel extends javax.swing.JPanel {

    private final PDC myController;



    /** The controller used to change and retrieve data. */
    //private final String myBudget;
    //private final String myBudget;




    public String getBudget(){
        return getBudget.getText();
    }

    /**
     * Creates new form budgetPanel
     * @param
     */
    public BudgetPanel(PDC myController) {
        //myBudget = theBudget;
        this.myController = myController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        budgetTitle = new javax.swing.JLabel();
        currentBudget = new javax.swing.JLabel();
        getBudget = new javax.swing.JTextField();
        dollarSign1 = new javax.swing.JLabel();
        Budget = new javax.swing.JLabel();
        dollarSign2 = new javax.swing.JLabel();
        showCurrentBudget = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        budgetTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        budgetTitle.setText("Budget :");

        currentBudget.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentBudget.setText("Current Budget :");

        getBudget.setText("Budget");
        getBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBudgetActionPerformed(evt);
            }
        });

        dollarSign1.setText("$");
        dollarSign1.setToolTipText("");

        Budget.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Budget.setText("Budget");

        dollarSign2.setText("$");
        dollarSign2.setToolTipText("");

        showCurrentBudget.setText("Current Budget");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmButton.setText("CONFIRM");
        confirmButton.setActionCommand("CONFIRM");
        /**confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });**/
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(budgetTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(currentBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(showCurrentBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getBudget))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dollarSign1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                                        .addComponent(dollarSign2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(Budget, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Budget, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(budgetTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dollarSign1))
                                .addGap(1, 1, 1)
                                .addComponent(confirmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(currentBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showCurrentBudget)
                                        .addComponent(dollarSign2))
                                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void getBudgetActionPerformed(java.awt.event.ActionEvent evt) {
        /**  String budgetText = getBudget.getText(); // Get the budget entered by the user

         // Pass the budget to the PDC or perform any other desired action

         myController.setProjectBudget(budgetText); // Assuming you have a `setBudget` method in your PDC class

         // You can also update the UI or perform any other necessary operations

         currentBudget.setText("Current Budget: " + budgetText);**/

    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        // TODO add your handling code here:
        String budgetText = getBudget.getText();

        try {
            BigDecimal budget = new BigDecimal(budgetText); // Parse the budget text to a BigDecimal value

            myController.setProjectBudget(budget); // Set the project budget in the PDC

            BigDecimal currentBudget = myController.calculateCurrentBudget();

            showCurrentBudget.setText(currentBudget.toString());

            // Check if the current budget is negative and display a dialog if true
            if (currentBudget.compareTo(BigDecimal.ZERO) < 0) {
                JOptionPane.showMessageDialog(this, "Warning: you should ask help from your mom.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Handle invalid input
            JOptionPane.showMessageDialog(this, "Invalid budget value. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Check if the current budget is negative and display a dialog if true

    }


    /**private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }**/


    // Variables declaration - do not modify
    private javax.swing.JLabel dollarSign1;
    private javax.swing.JLabel dollarSign2;
    private javax.swing.JLabel budgetTitle;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel currentBudget;
    private javax.swing.JTextField getBudget;
    private javax.swing.JLabel Budget;
    private javax.swing.JLabel showCurrentBudget;
    // End of variables declaration
}
