/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.PDC;

import java.util.Set;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.math.BigDecimal;


/**
 *
 * @author Jarvis
 */
public class ProjectList extends javax.swing.JPanel {

    private final PDC controller;

    private ProjectPanel pp;

    /** The DashBoardPanel that holds this List of Projects */
    private DashboardPanel dbp;

    private javax.swing.JPanel BudgetInfo; // Add the BudgetInfo variable

    /**
     * Creates new form ProjectList
     * @param controller
     */
    public ProjectList(final PDC controller, ProjectPanel pp) {
        this.pp = pp;
        this.dbp = (DashboardPanel)getParent();
        this.controller = controller;
        initComponents();
    }

    public ProjectPanel getProjectPanel() {
        return pp;
    }

    /**
     * Repopulates the User's List of Projects
     * @author Paul Schmidt
     */
    public void repopulateProjectsList() {
        ProjectList.removeAll();
        Set<String> s = controller.getProjectNames();
        for (String project : s) {
            ProjectsPanel p = new ProjectsPanel(project, controller);
            ProjectList.add(p);
        }
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProjectDialog = new javax.swing.JDialog();
        projectNameTextField = new javax.swing.JTextField();
        projectNameLabel = new javax.swing.JLabel();
        createProjectButton = new javax.swing.JButton();
        cancelProjectButton = new javax.swing.JButton();
        ProjectListTitle = new javax.swing.JPanel();
        ProjectAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ProjectList = new javax.swing.JPanel();

        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        projectNameLabel.setText("Project Name:");

        createProjectButton.setText("Create");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtoncreateProjectAction(evt);
            }
        });

        cancelProjectButton.setText("Cancel");
        cancelProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelProjectButtoncancelProjectAction(evt);
            }
        });

        javax.swing.GroupLayout createProjectDialogLayout = new javax.swing.GroupLayout(createProjectDialog.getContentPane());
        createProjectDialog.getContentPane().setLayout(createProjectDialogLayout);
        createProjectDialogLayout.setHorizontalGroup(
            createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createProjectDialogLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createProjectDialogLayout.createSequentialGroup()
                        .addComponent(projectNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelProjectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createProjectButton)
                .addContainerGap())
        );
        createProjectDialogLayout.setVerticalGroup(
            createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createProjectDialogLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProjectButton)
                    .addComponent(cancelProjectButton))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(250, 250, 250));

        ProjectListTitle.setBackground(new java.awt.Color(250, 250, 250));
        ProjectListTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ProjectListTitle.setPreferredSize(new java.awt.Dimension(200, 120));

        ProjectAdd.setBackground(new java.awt.Color(250, 250, 250));
        ProjectAdd.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ProjectAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-button.png"))); // NOI18N
        ProjectAdd.setAlignmentY(0.0F);
        ProjectAdd.setBorder(null);
        ProjectAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Projects List");

        javax.swing.GroupLayout ProjectListTitleLayout = new javax.swing.GroupLayout(ProjectListTitle);
        ProjectListTitle.setLayout(ProjectListTitleLayout);
        ProjectListTitleLayout.setHorizontalGroup(
            ProjectListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectListTitleLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProjectAdd)
                .addGap(14, 14, 14))
        );
        ProjectListTitleLayout.setVerticalGroup(
            ProjectListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectListTitleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(ProjectListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ProjectAdd))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ProjectList.setBackground(new java.awt.Color(250, 250, 250));
        ProjectList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ProjectList.setPreferredSize(new java.awt.Dimension(200, 120));
        Set<String> s = controller.getProjectNames();
        //ArrayList<String> arr = new ArrayList<>();
        for (String project : s) {
            ProjectsPanel p = new ProjectsPanel(project, controller);
            ProjectList.add(p);
        }
        ProjectList.setLayout(new javax.swing.BoxLayout(ProjectList, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addComponent(ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectAddActionPerformed
        createProjectDialog.pack();
        createProjectDialog.setLocationRelativeTo(null);
        projectNameTextField.setText("");
        createProjectDialog.setVisible(true);
    }//GEN-LAST:event_ProjectAddActionPerformed

    private void createProjectButtoncreateProjectAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtoncreateProjectAction
        try {
            controller.addNewProject(projectNameTextField.getText());
            dbp = (DashboardPanel)getParent();
            dbp.repopulateProjectPanel();
            this.ProjectList.add(new ProjectsPanel(this.projectNameTextField.getText(), controller));
            this.ProjectList.revalidate();
            this.ProjectList.repaint();
            createProjectDialog.dispose();

            AddBudgetPopUpPanel popUp = new AddBudgetPopUpPanel();

            int confirm = JOptionPane.showOptionDialog(null, popUp, "Budget", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null);
            try{
                if(confirm == 0){
                    System.out.println("Accept");
                    String projectBudgetString = popUp.getBudget();
                    BigDecimal projectBudget = new BigDecimal(projectBudgetString);
                    controller.setProjectBudget(projectBudget);
                    dbp.repopulateProjectPanel();
                    revalidate();
                    repaint();
                } else {
                    System.out.println("Cancel");
                }
            } catch (NullPointerException e){
                System.out.println("Error");
            }


        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createProjectButtoncreateProjectAction

    private void cancelProjectButtoncancelProjectAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelProjectButtoncancelProjectAction
        createProjectDialog.dispose();
    }//GEN-LAST:event_cancelProjectButtoncancelProjectAction

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProjectAdd;
    private javax.swing.JPanel ProjectList;
    private javax.swing.JPanel ProjectListTitle;
    private javax.swing.JButton cancelProjectButton;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JDialog createProjectDialog;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    // End of variables declaration//GEN-END:variables
}
