/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import control.PDC;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author David
 */
public class ProjectPanel extends javax.swing.JPanel {

    private final PDC myController;
    /**
     * Creates new form ProjectPanel
     * @param theController The data controller.
     */
    public ProjectPanel(final PDC theController) {
        myController = theController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectTitle = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TaskTitle = new javax.swing.JPanel();
        TrashButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PurchasesTitle = new javax.swing.JPanel();
        PurchaseAdd = new javax.swing.JButton();
        PurchasesLabel = new javax.swing.JLabel();
        Description = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        CostLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        BudgetInfo = new javax.swing.JPanel();
        BudgetLabel = new javax.swing.JLabel();
        TaskListTitle = new javax.swing.JPanel();
        TaskAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TaskList = new javax.swing.JPanel();
        PurchasesList = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(600, 500));

        ProjectTitle.setBackground(new java.awt.Color(250, 250, 250));
        ProjectTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ProjectTitle.setPreferredSize(new java.awt.Dimension(400, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setText(myController.getCurrProjectName());

        javax.swing.GroupLayout ProjectTitleLayout = new javax.swing.GroupLayout(ProjectTitle);
        ProjectTitle.setLayout(ProjectTitleLayout);
        ProjectTitleLayout.setHorizontalGroup(
            ProjectTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProjectTitleLayout.setVerticalGroup(
            ProjectTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(12, 12, 12))
        );

        TaskTitle.setBackground(new java.awt.Color(250, 250, 250));
        TaskTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TaskTitle.setPreferredSize(new java.awt.Dimension(400, 40));

        TrashButton.setBackground(new java.awt.Color(250, 250, 250));
        TrashButton.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        TrashButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash-bin.png"))); // NOI18N
        TrashButton.setAlignmentY(0.0F);
        TrashButton.setBorder(null);
        TrashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrashButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText(myController.getCurrTaskName());

        javax.swing.GroupLayout TaskTitleLayout = new javax.swing.GroupLayout(TaskTitle);
        TaskTitle.setLayout(TaskTitleLayout);
        TaskTitleLayout.setHorizontalGroup(
            TaskTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TrashButton)
                .addGap(7, 7, 7))
        );
        TaskTitleLayout.setVerticalGroup(
            TaskTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskTitleLayout.createSequentialGroup()
                .addGroup(TaskTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TaskTitleLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addGroup(TaskTitleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(TrashButton)))
                .addGap(8, 8, 8))
        );

        PurchasesTitle.setBackground(new java.awt.Color(250, 250, 250));
        PurchasesTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PurchasesTitle.setPreferredSize(new java.awt.Dimension(400, 40));

        PurchaseAdd.setBackground(new java.awt.Color(250, 250, 250));
        PurchaseAdd.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        PurchaseAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-button.png"))); // NOI18N
        PurchaseAdd.setAlignmentY(0.0F);
        PurchaseAdd.setBorder(null);
        PurchaseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseAddActionPerformed(evt);
            }
        });

        PurchasesLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        PurchasesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PurchasesLabel.setText("Purchases");
        PurchasesLabel.setAlignmentY(0.0F);
        PurchasesLabel.setPreferredSize(new java.awt.Dimension(67, 16));

        javax.swing.GroupLayout PurchasesTitleLayout = new javax.swing.GroupLayout(PurchasesTitle);
        PurchasesTitle.setLayout(PurchasesTitleLayout);
        PurchasesTitleLayout.setHorizontalGroup(
            PurchasesTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PurchasesTitleLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(PurchasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(PurchaseAdd)
                .addGap(10, 10, 10))
        );
        PurchasesTitleLayout.setVerticalGroup(
            PurchasesTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchasesTitleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PurchasesTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PurchaseAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PurchasesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        Description.setBackground(new java.awt.Color(250, 250, 250));
        Description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Description.setPreferredSize(new java.awt.Dimension(400, 50));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        nameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");

        CostLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        CostLabel.setText("Cost");

        StatusLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLabel.setText("Status");

        javax.swing.GroupLayout DescriptionLayout = new javax.swing.GroupLayout(Description);
        Description.setLayout(DescriptionLayout);
        DescriptionLayout.setHorizontalGroup(
            DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(nameLabel)
                .addGap(75, 75, 75)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CostLabel)
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(StatusLabel)
                .addGap(22, 22, 22))
        );
        DescriptionLayout.setVerticalGroup(
            DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescriptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3)
            .addGroup(DescriptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(CostLabel))
                .addGap(14, 14, 14))
            .addGroup(DescriptionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(StatusLabel)
                .addContainerGap())
        );

        BudgetInfo.setBackground(new java.awt.Color(250, 250, 250));
        BudgetInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        BudgetInfo.setPreferredSize(new java.awt.Dimension(200, 120));

        BudgetLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        BudgetLabel.setText("Budget");

        javax.swing.GroupLayout BudgetInfoLayout = new javax.swing.GroupLayout(BudgetInfo);
        BudgetInfo.setLayout(BudgetInfoLayout);
        BudgetInfoLayout.setHorizontalGroup(
            BudgetInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BudgetInfoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(BudgetLabel)
                .addGap(69, 69, 69))
        );
        BudgetInfoLayout.setVerticalGroup(
            BudgetInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BudgetInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BudgetLabel)
                .addGap(162, 162, 162))
        );

        TaskListTitle.setBackground(new java.awt.Color(250, 250, 250));
        TaskListTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TaskListTitle.setPreferredSize(new java.awt.Dimension(200, 120));

        TaskAdd.setBackground(new java.awt.Color(250, 250, 250));
        TaskAdd.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        TaskAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-button.png"))); // NOI18N
        TaskAdd.setAlignmentY(0.0F);
        TaskAdd.setBorder(null);
        TaskAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tasks List");

        javax.swing.GroupLayout TaskListTitleLayout = new javax.swing.GroupLayout(TaskListTitle);
        TaskListTitle.setLayout(TaskListTitleLayout);
        TaskListTitleLayout.setHorizontalGroup(
            TaskListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskListTitleLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(TaskAdd)
                .addGap(417, 417, 417))
        );
        TaskListTitleLayout.setVerticalGroup(
            TaskListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskListTitleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(TaskListTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TaskAdd))
                .addGap(264, 264, 264))
        );

        TaskList.setBackground(new java.awt.Color(250, 250, 250));
        TaskList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TaskList.setPreferredSize(new java.awt.Dimension(200, 120));
        ArrayList<String> arr = new ArrayList<>();
        arr.add("task 1");
        arr.add("task 2");
        for (String task : arr) {
            TaskPanel t = new TaskPanel(task, myController);
            TaskList.add(t);
        }
        TaskList.setLayout(new javax.swing.BoxLayout(TaskList, javax.swing.BoxLayout.Y_AXIS));

        PurchasesList.setBackground(new java.awt.Color(250, 250, 250));
        PurchasesList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PurchasesList.setPreferredSize(new java.awt.Dimension(200, 120));

        javax.swing.GroupLayout PurchasesListLayout = new javax.swing.GroupLayout(PurchasesList);
        PurchasesList.setLayout(PurchasesListLayout);
        PurchasesListLayout.setHorizontalGroup(
            PurchasesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PurchasesListLayout.setVerticalGroup(
            PurchasesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BudgetInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaskTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PurchasesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaskList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(PurchasesList, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BudgetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(TaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PurchasesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TaskListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(TaskList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(PurchasesList, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TaskAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskAddActionPerformed

    private void PurchaseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchaseAddActionPerformed

    private void TrashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrashButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrashButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BudgetInfo;
    private javax.swing.JLabel BudgetLabel;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JPanel Description;
    private javax.swing.JPanel ProjectTitle;
    private javax.swing.JButton PurchaseAdd;
    private javax.swing.JLabel PurchasesLabel;
    private javax.swing.JPanel PurchasesList;
    private javax.swing.JPanel PurchasesTitle;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton TaskAdd;
    private javax.swing.JPanel TaskList;
    private javax.swing.JPanel TaskListTitle;
    private javax.swing.JPanel TaskTitle;
    private javax.swing.JButton TrashButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
