/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import control.PDC;
import java.awt.Color;

/**
 *
 * @author Jarvis Kampe
 */
public class ProjectsPanel extends javax.swing.JPanel {

    private final String myProject;
    
    private final PDC myController;
    /** The currently selected Projects Panel*/
    static ProjectsPanel selectedProjectsPanel;
    /**
     * Creates new form TaskPanel
     */
    public ProjectsPanel(final String theProject, final PDC theController) {
        myProject = theProject;
        myController = theController;
        initComponents();
        if(myController.getCurrProjectName() != null
                && myController.getCurrProjectName().equals(myProject)) {
            if (selectedProjectsPanel != null) {
                selectedProjectsPanel.setBackground(new Color(250,250,250));
            }
            selectedProjectsPanel = this;
            setBackground(Color.LIGHT_GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaskName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(200, 30));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setCurrentProjectAction(evt);
            }
        });

        TaskName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        TaskName.setText(myProject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(TaskName)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(TaskName)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets the currently selected Project based on the ProjectsPanel that was clicked.
     * Changes the color of the Panel for User visual feedback.
     * @author Jarvis Kampe
     * @author Paul Schmidt
     * @param evt the button click event.
     */
    private void setCurrentProjectAction(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        myController.setCurrentProject(this.TaskName.getText());
        DashboardPanel db = (DashboardPanel)getParent().getParent().getParent();
        if(selectedProjectsPanel != null) {
            selectedProjectsPanel.setBackground(new Color(250, 250, 250));
        }
        selectedProjectsPanel = this;
        selectedProjectsPanel.setBackground(Color.LIGHT_GRAY);
        db.repopulateProjectPanel();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TaskName;
    // End of variables declaration//GEN-END:variables
}
