/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.PDC;

import javax.swing.*;

/**
 * A Panel used to represent a purchase.
 * @author Derek J. Ruiz Garcia
 * @version 6/3/2023
 */
public class PurchasePanel extends javax.swing.JPanel {

    /** The name of the purchase represented by this panel */
    private final String myPurchaseName;

    /** The cot of the purchase represented by this panel */
    private final String myCost;

    /** The controller used to change and retrieve data. */
    private final PDC myController;

    /**
     * A constructor for the purchase panel.
     * @param thePurchaseName the name of the purchase this panel will represent as a string.
     * @param theCost the cost of the purchase as a string linked to this panel.
     * @param theStatus the completed status of the purchase as a boolean.
     * @param theController the PDC controller that this panel will use to update the data.
     * @author Derek J. Ruiz Garcia
     */
    public PurchasePanel(String thePurchaseName, String theCost, boolean theStatus, PDC theController) {
        myPurchaseName = thePurchaseName;
        myCost = theCost;
        myController = theController;
        initComponents();
        purchaseLabel.setText(thePurchaseName);
        costLabel.setText(theCost);
        statusCheckBox.setSelected(theStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        costLabel = new javax.swing.JLabel();
        statusCheckBox = new javax.swing.JCheckBox();
        purchaseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(400, 30));

        costLabel.setText("<Purchase Cost>");

        statusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxStatusActionPerformed(evt);
            }
        });

        purchaseLabel.setText("<PurchaseName>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(purchaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(costLabel)
                .addGap(48, 48, 48)
                .addComponent(statusCheckBox)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusCheckBox)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costLabel)
                        .addComponent(purchaseLabel)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action performed listener for the checkbox.
     * @param evt the event linked to the checkbox
     * @author Derek J. Ruiz Garcia
     */
    private void checkBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        AbstractButton abs = (AbstractButton) evt.getSource();
        myController.setPurchaseStatus(myPurchaseName, abs.getModel().isSelected());
        revalidate();
        repaint();
    }//GEN-LAST:event_statusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel purchaseLabel;
    private javax.swing.JCheckBox statusCheckBox;
    // End of variables declaration//GEN-END:variables
}
