/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.PDC;

import javax.swing.*;

/**
 *
 * @author derek
 */
public class PurchasePanel extends javax.swing.JPanel {

    /** The name of the purchase represented by this panel */
    private final String myPurchaseName;

    /** The cot of the purchase represented by this panel */
    private final String myCost;

    /** The controller used to change and retrieve data. */
    private final PDC myController;

    /**
     * Creates new form PurchasePanel
     */
    public PurchasePanel(String thePurchaseName, String theCost, PDC theController) {
        myPurchaseName = thePurchaseName;
        myCost = theCost;
        myController = theController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        costLabel = new javax.swing.JLabel();
        checkBoxStatus = new javax.swing.JCheckBox();
        purchaseNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(400, 30));

        costLabel.setText(myCost);

        checkBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxStatusActionPerformed(evt);
            }
        });

        /** TODO Testing error for getting a task form a project that doesn't exist */
//        status.setSelected(myController.getTaskStatus(myTask));
        checkBoxStatus.setSelected(false);

        purchaseNameLabel.setText(myPurchaseName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(purchaseNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(costLabel)
                .addGap(48, 48, 48)
                .addComponent(checkBoxStatus)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBoxStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costLabel)
                        .addComponent(purchaseNameLabel)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        AbstractButton abs = (AbstractButton) evt.getSource();
//        myController.setPurchaseStatus(myPurchaseName, abs.getModel().isSelected());
    }//GEN-LAST:event_statusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxStatus;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel purchaseNameLabel;
    // End of variables declaration//GEN-END:variables
}
